import { AuthResponse, User, Student, Lecturer, Course, CourseModule, ClassSession, AttendanceRecord, Alert } from '../types';
export declare function loginUser(email: string, password: string): Promise<AuthResponse>;
export declare function logout(): Promise<void>;
export declare function getCurrentUser(): Promise<User>;
export declare function getStudents(limit?: number, offset?: number): Promise<Student[]>;
export declare function getStudent(id: string): Promise<Student>;
export declare function createStudent(data: Partial<Student>): Promise<Student>;
export declare function updateStudent(id: string, data: Partial<Student>): Promise<Student>;
export declare function deleteStudent(id: string): Promise<void>;
export declare function getLecturers(limit?: number, offset?: number): Promise<Lecturer[]>;
export declare function getLecturer(id: string): Promise<Lecturer>;
export declare function createLecturer(data: Partial<Lecturer>): Promise<Lecturer>;
export declare function updateLecturer(id: string, data: Partial<Lecturer>): Promise<Lecturer>;
export declare function deleteLecturer(id: string): Promise<void>;
export declare function getCourses(): Promise<Course[]>;
export declare function getCourse(id: string): Promise<Course>;
export declare function createCourse(data: Partial<Course>): Promise<Course>;
export declare function updateCourse(id: string, data: Partial<Course>): Promise<Course>;
export declare function deleteCourse(id: string): Promise<void>;
export declare function getCourseModules(courseId: string): Promise<CourseModule[]>;
export declare function createCourseModule(courseId: string, data: Partial<CourseModule>): Promise<CourseModule>;
export declare function updateCourseModule(moduleId: string, data: Partial<CourseModule>): Promise<CourseModule>;
export declare function deleteCourseModule(moduleId: string): Promise<void>;
export declare function getSessions(limit?: number, offset?: number): Promise<ClassSession[]>;
export declare function getPublicSessions(limit?: number, offset?: number): Promise<ClassSession[]>;
export declare function getSession(id: string): Promise<ClassSession>;
export declare function createSession(data: Partial<ClassSession>): Promise<ClassSession>;
export declare function updateSession(id: string, data: Partial<ClassSession>): Promise<ClassSession>;
export declare function deleteSession(id: string): Promise<void>;
export declare function getAttendance(limit?: number, offset?: number): Promise<AttendanceRecord[]>;
export declare function recordAttendance(data: Partial<AttendanceRecord>): Promise<AttendanceRecord>;
export declare function recordAttendanceByFace(faceData: string, studentId?: string): Promise<AttendanceRecord>;
export declare function getAlerts(): Promise<Alert[]>;
export declare function markAlertAsRead(id: string): Promise<Alert>;
export declare function getAttendanceReport(): Promise<any>;
export declare function getStudentReport(studentId: string): Promise<any>;
export declare function changeUserPassword(currentPassword: string | undefined, newPassword: string): Promise<void>;
export declare function verifyFaceAttendance(biometricHash: string, confidence: number, descriptorData: string): Promise<any>;
export declare function getFaceEnrollmentStatus(studentId: string): Promise<any>;
export declare function enrollFaceBiometric(studentId: string, biometricHash: string, descriptorData: string, confidence: number): Promise<any>;
export declare function revokeBiometricEnrollment(studentId: string): Promise<any>;
//# sourceMappingURL=api.d.ts.map